### ISSUE TITLE
What is the licence of code snippets on your blog?

### ISSUE THREAD

**Issue by pspacek** [kevin-brown/blog.kevin-brown.com#6]
Hello!

What is license of code snippets on your blog? Could it be MIT or GPL3? :-)

Thank you for answers!

**Comment by kevin-brown** [comment]
Which snippets specifically are you looking for the license for?

I'll go back through the posts I've done and determine what the license needs to be. And then I'll add a note in the footer about licensing.

**Comment by pspacek** [comment]
Hello,

right now I'm very interested in https://blog.kevin-brown.com/programming/2014/09/24/combining-autotools-and-setuptools.html . I would like to use it GPLv3 projekt called [FreeIPA](http://www.freeipa.org/).

Thank you for considering this!
